<?xml version="1.0"?>
<robot name="dribot" xmlns:xacro="http://ros.org/wiki/xacro">

  <xacro:property name="base_radius" value="0.2"/>
  <xacro:property name="base_height" value="0.20"/>
  <xacro:property name="base_mass" value="18"/>

  <xacro:property name="wheel_radius" value="0.075"/>
  <xacro:property name="wheel_width" value="0.03"/>
  <xacro:property name="wheel_mass" value="0.5"/>

  <xacro:property name="wheel_ygap" value="0.01"/>
  <xacro:property name="wheel_zoff" value="${wheel_radius}"/>

  <xacro:property name="base_to_caster" value="0.13"/>

  <xacro:include filename="$(find dribot_description)/urdf/macros.xacro" />
  <xacro:include filename="$(find dribot_description)/urdf/wheel.xacro" />
  <xacro:include filename="$(find dribot_description)/urdf/caster.xacro" />

  <link name="base_link">
    <visual>
      <origin xyz="0 0 0" rpy="0 0 0"/>
      <geometry>
        <cylinder radius="${base_radius}" length="${base_height}"/>
      </geometry>
    </visual>

    <collision>
      <origin xyz="0 0 0" rpy="0 0 0"/>
      <geometry>
        <cylinder radius="${base_radius}" length="${base_height}"/>
      </geometry>
    </collision>

    <xacro:cylinder_inertia m="${base_mass}" r="${base_radius}" h="${base_height}" roll="0"/>
  </link>

  <link name="base_footprint">
  </link>

  <joint name="base_joint" type="fixed">
    <parent link="base_link"/>
    <child link="base_footprint"/>
    <origin xyz="0.0 0.0 ${-(wheel_radius+wheel_zoff)}" rpy="0 0 0"/>
  </joint>

  <xacro:wheel prefix="wheel_left" x_pos="0" y_pos="${base_radius+wheel_ygap}" />
  <xacro:wheel prefix="wheel_right" x_pos="0" y_pos="-${base_radius+wheel_ygap}" />

  <xacro:caster prefix="caster_front" x_pos="${base_to_caster}"
                radius="${(wheel_radius+wheel_zoff-(base_height/2))}"/>
  <xacro:caster prefix="caster_rear" x_pos="${-base_to_caster}"
                radius="${(wheel_radius+wheel_zoff-(base_height/2))}"/>

</robot>
